### ISSUE TITLE
allow to anonymize user PII

### ISSUE THREAD

**Issue by noerw** [fs-geofs/ErstiWeTool#12]
storing PII is a liability. also, #11 

we might want to keep non-PII for archiving purposes, so instead of deleting each users row, we could replace name, date of birth, phone with placeholders, after the event was conducted

**Comment by SpeckiJ** [comment]
I don't see any merit in keeping the specific user rows after anonymization.

For archiving purposes it would suffice to save completely anonymized general statistics (e.g. no. of participants, distribution of studies, etc.) and completely delete the user information.

For sake of simplicity this data could even be stored outside of the Database in a File storage as it is not needed inside the application itself.

**Comment by noerw** [comment]
I don't see any merit in collecting PII in the first place :^)
:crossed_swords: `f i g h t !`
