### ISSUE TITLE
MAJOR: Endpoint that accepts the filled out form requests authentication

### ISSUE THREAD

**Issue by christophfriedrich** [fs-geofs/ErstiWeTool#18]
Wir mussten gerade das Backend-Passwort auf jedem der Rechner eingeben, um die Anmeldung zu retten...

**Comment by noerw** [comment]
wtf
vermute https://github.com/fs-geofs/ErstiWeTool/commit/da45ab3b0bbe9f46d06dc41b987c86e6a9a76792#diff-6acab4546214e3d452414e9adcb835d0R10 ist schuld, aber das dürfte sich nicht auf irgendwelche api routen beziehen??
