### ISSUE TITLE
make tokens more human friendly

### ISSUE THREAD

**Issue by noerw** [fs-geofs/ErstiWeTool#5]
At least avoid the hard to distinguish letters `0 <-> O`, `1 <-> l`

Even better: use a random word generator! Either..
- generate random pseudo words using a markov chain and a dictionary
- concatenate random words

The length should be definitily more than 8 characters, to make bruteforcing harder

**Comment by SpeckiJ** [comment]
changes for hard to distinguish letters is Implemented in branch https://github.com/fs-geofs/ErstiWeTool/tree/feature/enhancements
